##https://marketplace.upbound.io/providers/crossplane-contrib/provider-aws/v0.54.2/resources/s3.aws.crossplane.io/Bucket/v1beta1
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: my-bucket
spec:
  forProvider:
    locationConstraint: eu-central-1
    versioningConfiguration:
      status: Enabled
    tagging:
      tagSet:
        - key: "Owner"
          value: "Backend Team"
  providerConfigRef:
    name: aws-provider-localstack
