apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: imported
spec:
  # https://docs.crossplane.io/latest/managed-resources/managed-resources/#managementpolicies
  # managementPolicies: ["Create", "Delete", "Update", "Observe", "LateInitialize"]
  managementPolicies: ["Observe"]
  # managementPolicies: ["*"]
  forProvider:
    locationConstraint: eu-central-1
    versioningConfiguration:
      status: Enabled
    tagging:
      tagSet:
        - key: "Owner"
          value: "Backend Team"
  providerConfigRef:
    name: aws-provider-localstack

