apiVersion: v1
kind: Secret
metadata:
  name: localstack-creds
  namespace: crossplane-system
stringData:
  credentials: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test
---
#https://marketplace.upbound.io/providers/crossplane-contrib/provider-aws/v0.54.2/resources/aws.crossplane.io/ProviderConfig/v1beta1
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider-localstack
spec:
  credentials:
    secretRef:
      key: credentials
      name: localstack-creds
      namespace: crossplane-system
    source: Secret
  endpoint:
    hostnameImmutable: true
    url:
      static: http://localstack.localstack:4566
      type: Static